In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/training_data.csv", encoding="ISO-8859-1")

### Determine the general format of the dataset

The goal of this section is to get an initial understanding of the dataset's overall structure. This includes identifying whether the dataset contains any missing or duplicate values and reviewing its general shape.

In [2]:
df.head(5)

,Workout ID,Date,Distance (km),Duration (min),Calories (kcal),Average Pace (min/km),Average Speed (km/h),Max Speed (km/h),Elevation Gain (m),Elevation Loss (m),Start Time,Temperature (C),Wind Speed (km/h),Humidity (%)
0,1,14/06/2023,4.37,20:00,316,04:35,13.1,18.1,13,13.0,19:11,22.0,11.0,80.0
1,2,19/06/2023,4.45,20:00,315,04:29,13.3,15.5,12,13.0,20:06,29.0,14.0,53.0
2,3,01/07/2023,5.26,25:01,395,04:45,12.6,15.1,12,14.0,12:09,22.0,8.0,79.0
3,4,21/08/2023,4.03,20:02,312,04:58,12.1,14.3,0,10.0,19:03,34.0,8.0,42.0
4,5,04/10/2023,3.76,20:01,305,05:19,11.3,13.6,9,13.0,17:03,25.0,13.0,68.0

In [3]:
print("\nDataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Workout ID             46 non-null     int64
 1   Date                   46 non-null     object
 2   Distance (km)          46 non-null     float64
 3   Duration (min)         46 non-null     object
 4   Calories (kcal)        46 non-null     int64
 5   Average Pace (min/km)  46 non-null     object
 6   Average Speed (km/h)   46 non-null     float64
 7   Max Speed (km/h)       46 non-null     float64
 8   Elevation Gain (m)     44 non-null     object
 9   Elevation Loss (m)     44 non-null     float64
 10  Start Time             45 non-null     object
 11  Temperature (C)        45 non-null     float64
 12  Wind Speed (km/h)      41 non-null     float64
 13  Humidity (%)           41 non-null     float64
dtypes: float64(7), int64(2), object(5)
memory usage: 5.2+ KB

In [4]:
print("\nMissing Values per column:")
df.isnull().sum()

Missing Values per column:

Workout ID               0
Date                     0
Distance (km)            0
Duration (min)           0
Calories (kcal)          0
Average Pace (min/km)    0
Average Speed (km/h)     0
Max Speed (km/h)         0
Elevation Gain (m)       2
Elevation Loss (m)       2
Start Time               1
Temperature (C)          1
Wind Speed (km/h)        5
Humidity (%)             5
dtype: int64

In [5]:
print(f"\nNumber of duplicate rows in the dataset: {df.duplicated().sum()}")

Number of duplicate rows in the dataset: 0

### How many rows and columns are in the dataset?

This section answers the question by inspecting the dataset's shape to understand its overall structure.

In [6]:
rows, cols = df.shape
print(f"The dataset contains {rows} rows and {cols} columns")

The dataset contains 46 rows and 14 columns

### What are the names and data types of each column?

In this section, we examine the dataset's structure by listing the column names and their corresponding data types.

In [7]:
df.dtypes

Workout ID                 int64
Date                      object
Distance (km)            float64
Duration (min)            object
Calories (kcal)            int64
Average Pace (min/km)     object
Average Speed (km/h)     float64
Max Speed (km/h)         float64
Elevation Gain (m)        object
Elevation Loss (m)       float64
Start Time                object
Temperature (C)          float64
Wind Speed (km/h)        float64
Humidity (%)             float64
dtype: object

### Analyze the distribution of numerical variables

This section aims to provide a statistical summary of all numerical columns in the dataset.

In [13]:
print("Statistical summary of numerical variables:")
df.loc[:, df.columns != "Workout ID"].describe()

Statistical summary of numerical variables:

,Distance (km),Calories (kcal),Average Speed (km/h),Max Speed (km/h),Elevation Loss (m),Temperature (C),Wind Speed (km/h),Humidity (%)
count,46.000000,46.000000,46.000000,46.000000,44.000000,45.000000,41.000000,41.000000
mean,3.876087,288.434783,13.915217,16.850000,14.045455,15.333333,11.000000,70.317073
std,2.014538,160.167642,1.570558,1.828873,6.884274,7.507572,2.924038,18.028365
min,1.000000,67.000000,11.100000,13.600000,0.000000,2.000000,5.000000,38.000000
25%,3.002500,228.500000,12.800000,15.425000,10.000000,9.000000,10.000000,61.000000
50%,4.045000,310.000000,13.550000,16.900000,13.000000,16.000000,10.000000,67.000000
75%,4.837500,316.750000,14.950000,17.775000,15.000000,21.000000,13.000000,86.000000
max,10.010000,811.000000,16.800000,21.200000,31.000000,34.000000,18.000000,100.000000

#### Observations from the Distribution Analysis

1. The column `Workout ID` is numerical but holds unique identifiers, which are not relevant for statistical analysis.
2. The `Duration (min)` column is in string format (object), preventing inclusion in numerical analyses. 
   - Future Action: Convert this column to seconds for uniformity and analysis.
   
3. The `Elevation Gain` column, although numerical, is stored as an object and should be converted to an integer.