## Temporal Data Analysis for Workouts

In this notebook, we will perform the following temporal analyses on the processed workout data:

1. Identify impossible dates: Detect and handle dates like "31st April," "29th February" in non-leap years, or future dates.
2. Identify duplicate dates: Check if any workout entries are duplicated for the same date.
3. Identify inactivity periods: Find gaps where no workouts were recorded.
4. Analyze time trends: Analyze trends in the data over time (e.g., average pace by month/year).
5. Identify seasonal patterns: Explore any seasonal patterns in workout frequency or performance.
6. Make future predictions: Predict workout frequency or performance for the upcoming month.

In [6]:
import pandas as pd
import os
os.chdir("C:/Users/Vale/Runalyze")

df = pd.read_csv("data/processed/processed_data.csv")
df.head(5)

,Workout ID,Date,Distance (km),Duration (min),Calories (kcal),Average Pace (min/km),Average Speed (km/h),Max Speed (km/h),Elevation Gain (m),Elevation Loss (m),Start Time,Temperature (C),Wind Speed (km/h),Humidity (%),Duration (sec),Average Pace (sec/km)
0,1,14/06/2023,4.37,20:00,316,04:35,13.1,18.1,13.0,13.0,19:11,22.0,11.0,80.0,1200,275
1,2,19/06/2023,4.45,20:00,315,04:29,13.3,15.5,12.0,13.0,20:06,29.0,14.0,53.0,1200,269
2,3,01/07/2023,5.26,25:01,395,04:45,12.6,15.1,12.0,14.0,12:09,22.0,8.0,79.0,1501,285
3,4,21/08/2023,4.03,20:02,312,04:58,12.1,14.3,0.0,10.0,19:03,34.0,8.0,42.0,1202,298
4,5,04/10/2023,3.76,20:01,305,05:19,11.3,13.6,9.0,13.0,17:03,25.0,13.0,68.0,1201,319

### Identify impossible dates

#### Future dates

In [12]:
# convert column 'Date' to pandas datetime object: invalid parsing will be set as NaT
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', dayfirst=True)

df.head(5)

,Workout ID,Date,Distance (km),Duration (min),Calories (kcal),Average Pace (min/km),Average Speed (km/h),Max Speed (km/h),Elevation Gain (m),Elevation Loss (m),Start Time,Temperature (C),Wind Speed (km/h),Humidity (%),Duration (sec),Average Pace (sec/km)
0,1,2023-06-14,4.37,20:00,316,04:35,13.1,18.1,13.0,13.0,19:11,22.0,11.0,80.0,1200,275
1,2,2023-06-19,4.45,20:00,315,04:29,13.3,15.5,12.0,13.0,20:06,29.0,14.0,53.0,1200,269
2,3,2023-07-01,5.26,25:01,395,04:45,12.6,15.1,12.0,14.0,12:09,22.0,8.0,79.0,1501,285
3,4,2023-08-21,4.03,20:02,312,04:58,12.1,14.3,0.0,10.0,19:03,34.0,8.0,42.0,1202,298
4,5,2023-10-04,3.76,20:01,305,05:19,11.3,13.6,9.0,13.0,17:03,25.0,13.0,68.0,1201,319

In [14]:
df.dtypes

Workout ID                        int64
Date                     datetime64[ns]
Distance (km)                   float64
Duration (min)                   object
Calories (kcal)                   int64
Average Pace (min/km)            object
Average Speed (km/h)            float64
Max Speed (km/h)                float64
Elevation Gain (m)              float64
Elevation Loss (m)              float64
Start Time                       object
Temperature (C)                 float64
Wind Speed (km/h)               float64
Humidity (%)                    float64
Duration (sec)                    int64
Average Pace (sec/km)             int64
dtype: object

In [33]:
from datetime import datetime

pd_today = pd.to_datetime(datetime.today(), format="%Y/%m/%d")
pd_today

Timestamp('2024-12-02 10:30:49.263933')

In [ ]:
future_dates = df[df['Date'] > pd]